.PHONY: all
all:	libgresb-dpu libgresb-pc

libgresb-dpu:
#	make -f ./Makefile-dpu.mk

libgresb-pc:
	make -f ./Makefile-pc.mk

.PHONY: clean
.IGNORE: clean
clean:
#	make -f ./Makefile-dpu.mk clean
	make -f ./Makefile-pc.mk clean
